#!/usr/bin/python

import sys
import ConfigParser
from pprint import pprint



def load_conf(filename):
    cp = ConfigParser.RawConfigParser()
    cp.read(filename)
    dic = {}
    for section in cp.sections():
        for key, value in cp.items(section):
            dic['%s:%s' % (section, key)] = value
    return dic

conf = load_conf("/etc/default/sjconf")
LOCAL_FILE=conf["conf:base_path"] + "/local.ini"
BASE_FILE=conf["conf:base_path"] + "/base.ini"

sys.path.insert(1, conf["conf:plugins_path"])

import decoder, dvb, iptables, \
       network, openvpn, postgresql, \
       proftpd, rxtxmanager, shaping, \
       sjfsd, snmpd, test, toolbox

PLUGINS = [decoder, dvb, iptables, \
           network, openvpn, postgresql, \
           proftpd, rxtxmanager, shaping, \
           sjfsd, snmpd, test, toolbox]

base   = load_conf(BASE_FILE)
local  = load_conf(LOCAL_FILE)
config = dict(base)

config.update(local)

for plugin in PLUGINS:
    plugin.init(base, local, config)

pprint(config)

